# Build a Qt project on Ubuntu
name: Build on Ubuntu

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.0'
        host: 'linux'
        target: 'desktop'
        modules: 'quick core qml gui'
    - name: qmake
      run: qmake .
    - name: make
      run: make
    - name: make check
      run: make check

#    - name: make distcheck
#      run: make distcheck
