# Build a Qt project on macOS
name: Build on macOS

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.8'
        host: 'mac'
        target: 'desktop'
        modules: 'quick core'
    - name: qmake
      run: qmake .
    - name: make
      run: make
    - name: make check
      run: make check

#    - name: make distcheck
#      run: make distcheck
