# Build a Qt project on Windows
name: Build on Windows

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.8'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2017_64'
        modules: 'quick core'
    - name: qmake
      run: qmake .
    - name: make
      run: make
    - name: make check
      run: make check

#    - name: make distcheck
#      run: make distcheck
